### ISSUE TITLE
Failed to establish JMX connection

### ISSUE THREAD

**Issue by lapo-luchini** [thelastpickle/cassandra-reaper#1100]
I have a remote DC wich is behind NAT… ports are mapped to an external IP address and I'm using `-Djava.rmi.server.hostname=public IPv4 address` and `nodetool gossip` shows the externally-reachable address, but Reaper is still trying to reach the local address:

```
Caused by: io.cassandrareaper.ReaperException: Failure when establishing JMX connection to 192.168.2.60:7199
```

Is there  way to force a manual address mapping and/or using the public RMI server hostname address?

**Comment by rss04** [comment]
Within the reaper config...try setting cassandra contact points to public ip and see if that fixes the issue

**Comment by rss04** [comment]
Can you please provide more context on your reaper configuration as how you are trying to discover the cluster from reaper using ?

**Comment by lapo-luchini** [comment]
Yes, I have a production cluster where each node is on public IP address, and those are easily reachable by Reaper, but I also have a single-node secondary DC used for disaster recovery and that node is behind NAT… the 7199 port is mapped on the border firewall to reach the correct host, and I specified the public IP in `-Djava.rmi.server.hostname` in the node configuration, this way `nodetool` works as expected (e.g. `nodetool gossip` reports the correct public IP, not `192.168.2.60`) and Reaper did as well, up to a few versions ago.

Lately though I've been getting that error, where the IP that Reaper is trying to reach is the private one the node have behind NAT, not the public one where it is mapped (and present in Java RMI configuration).

**Comment by lapo-luchini** [comment]
Regarding Reaper configuration:

```
repairParallelism: DATACENTER_AWARE
storageType: cassandra
useAddressTranslator: false
datacenterAvailability: ALL
jmxAuth:
  username: $user
  password: $pwd
cassandra:
  clusterName: "$cluster"
  contactPoints: ["$host"]
  keyspace: reaper_db
  loadBalancingPolicy:
    type: tokenAware
    shuffleReplicas: true
    subPolicy:
      type: dcAwareRoundRobin
      localDC: $dc1
      usedHostsPerRemoteDC: 0
      allowRemoteDCsForLocalConsistencyLevel: false
```

**Comment by Skunnyk** [comment]
Maybe `jmxAddressTranslator` option can help you ? https://cassandra-reaper.io/docs/configuration/reaper_specific/

**Comment by lapo-luchini** [comment]
Yes, I tried this way and it works as a nice work-around:

```
jmxAddressTranslator:
  type: multiIpPerNode
  ipTranslations:
  - from: 192.168.2.60
    to: (FQDN)
```

Funny thing, now that the node gets contacted correctly, the WebUI interface shows the correct (external) IP address that the node's JMX advertises (the one set in `-Djava.rmi.server.hostname` and shown also by `nodetool gossip`)… I wonder if that gets back-translated from the manually translated FQDN or if it is the number received via JMX.
