### ISSUE TITLE
No ability to login using simple PasswordAuthenticator?

### ISSUE THREAD

**Issue by alextechnology** [thelastpickle/cassandra-reaper#1202]
I just enabled `authenticator: PasswordAuthenticator` in my 6 node cluster and was able to connect using both cqlsh and Python drivers - the latter using `PlainTextAuthProvider`.  Unfortunately, I don't see any means to use credentials in the Reaper docs nor did I see any reference to driver `AuthProvider` settings anywhere in the Reaper source after a quick glance.  To clarify, I'm not worried about the WebUI Shiro auth, nor can I use JMX as my deployment requires SIDECAR - just Cassandra basic user/pass authentication.

Can Reaper work with Cassandra implementing authenticator/authorizer/role_manager security in SIDECAR mode??

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1554) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1554
┆priority: Medium

**Comment by adejanovski** [comment]
You'll find a sample in the documentation that will show you how to pass credentials to the driver in Reaper: http://cassandra-reaper.io/docs/configuration/backend_specific/

```
cassandra:
  clusterName: "test"
  contactPoints: ["127.0.0.1"]
  port: 9042
  keyspace: reaper_db
  loadBalancingPolicy:
    type: tokenAware
    shuffleReplicas: true
    subPolicy:
      type: dcAwareRoundRobin
      localDC:
      usedHostsPerRemoteDC: 0
      allowRemoteDCsForLocalConsistencyLevel: false
  authProvider:
    type: plainText
    username: cassandra
    password: cassandra
```

Let me know if that works for you.
