### ISSUE TITLE
Reaper can't start

### ISSUE THREAD

**Issue by engrkenjitanaka** [thelastpickle/cassandra-reaper#1259]
Getting this error when starting cassandra-reaper. Not too sure what's causing it

```
ERROR  [2023-01-05 11:49:21,989] [main] i.c.ReaperApplication - Storage is not ready yet, trying again to connect shortly...
java.lang.IllegalArgumentException: A health check named cassandra.cluster-name already exists
```

Backend config looks like this
```
cassandra:
clusterName: "cluster-name"
contactPoints: ["172.36.1.1", "172.36.1.2", "172.36.1.3"]
port: 9042
keyspace: reaper_db
loadBalancingPolicy:
  type: tokenAware
  shuffleReplicas: true
  subPolicy:
    type: dcAwareRoundRobin
    localDC:
    usedHostsPerRemoteDC: 0
    allowRemoteDCsForLocalConsistencyLevel: false
```
