### ISSUE TITLE
AutoScheduler ignoring config params

### ISSUE THREAD

**Issue by nvlan** [thelastpickle/cassandra-reaper#1329]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=34410028)

Hello,
I'm using reaper 3.2.0 with several cassandra 2.1.5 clusters. With autoscheduler enabled, every schedule that gets created has the same configuration regarding interval, segments per node, threads and so on. If I create a schedule by hand on the UI, I can specify the parameters I wish but in this case I don't quite understand what's the purpose of configuring multiple parameters that the autoscheduler will simply ignore. My current config is as follows:

```
segmentCountPerNode: 8
repairParallelism: PARALLEL
repairIntensity: 0.9
maxPendingCompactions: 20
scheduleDaysBetween: 14
repairRunThreadCount: 8
hangingRepairTimeoutMins: 10
storageType: cassandra
enableCrossOrigin: true
incrementalRepair: false
blacklistTwcsTables: true
enableDynamicSeedList: true
repairManagerSchedulingIntervalSeconds: 30
jmxConnectionTimeoutInSeconds: 20
useAddressTranslator: false
maxParallelRepairs: 4

datacenterAvailability: ALL

autoScheduling:
  enabled: true
  initialDelayPeriod: PT15S
  periodBetweenPolls: PT10M
  timeBeforeFirstSchedule: PT5M
  scheduleSpreadPeriod: PT6H
  adaptive: true
  incremental: false
  percentUnrepairedThreshold: 20

logging:
  level: DEBUG
  loggers: ${REAPER_LOGGING_LOGGERS}
  appenders:
    - type: console
      logFormat: "%-6level [%d] [%t] %logger{5} - %msg %n"
      threshold: DEBUG

server:
  type: default
  applicationConnectors:
    - type: http
      port: 8080
      bindHost: 0.0.0.0
  adminConnectors:
    - type: http
      port: 8081
      bindHost: 0.0.0.0
  requestLog:
    appenders: []
activateQueryLogger: false

cassandra:
  clusterName: reaper-cluster
  contactPoints: [1.2.3.4]
  port: 9042
  keyspace: reaper_db
  loadBalancingPolicy:
    type: tokenAware
    shuffleReplicas: true
    subPolicy:
      type: dcAwareRoundRobin
      localDC: 
      usedHostsPerRemoteDC: 0
      allowRemoteDCsForLocalConsistencyLevel: false
  authProvider:
    type: plainText
    username: ""
    password: ""
  ssl:
    type: jdk
accessControl:
  sessionTimeout: PT10M
  shiro:
    iniConfigs: ["file:/etc/cassandra-reaper/shiro.ini"]
```

Is this an expected behavior? Is there any way of specifying the schedule config for the autoscheduler? 
Thanks a lot!

┆Issue is synchronized with this [Jira Story](https://datastax.jira.com/browse/REAP-44) by [Unito](https://www.unito.io)
┆Issue Number: REAP-44
