### ISSUE TITLE
No Support for SSL on WebUI/AdminUI in Docker Container

### ISSUE THREAD

**Issue by jlevy8** [thelastpickle/cassandra-reaper#1335]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=35257238)

There does not appear to be any option to set `type: https` or additional `keyStorePath` and `keyStorePassword` parameters under `server:` config in Docker Entrypoint Scripts via Env Variables

Can these be added?
Looking to configure something like this

```
server:
  type: default
  applicationConnectors:
    - type: https
      port: 8080
      bindHost: 0.0.0.0
      keyStorePath: <Keystore File Path>
      keyStorePassword: <Keystore Password>
  adminConnectors:
    - type: https
      port: 8081
      bindHost: 0.0.0.0
      keyStorePath: <Keystore File Path>
      keyStorePassword: <Keystore Password>
```

But it appears that this defaults to `http` and does not support the additional option SSL configuration parameters

┆Issue is synchronized with this [Jira Story](https://datastax.jira.com/browse/REAP-38) by [Unito](https://www.unito.io)
┆Issue Number: REAP-38
