### ISSUE TITLE
Problem on CR 4.0.0 beta1

### ISSUE THREAD

**Issue by ddimanss** [thelastpickle/cassandra-reaper#1565]
Start new cassandra-reaper and in config have
```
storageType: cassandra
cassandra:
  type: basic
  contactPoints:
    - host: somehost
      port: 9042
  sessionName: cluster-name-session
  sessionKeyspaceName: cluster_name_cassandra_reaper
authProvider:
    type: plain-text
    username: cluster_name_db_user
    password: *
```

but get error 
`org.cognitor.cassandra.migration.MigrationException: Error during migration of script 034_init_reaper_db.cql while executing 'CREATE TABLE IF NOT EXISTS reaper_db.cluster `

`Caused by: com.datastax.oss.driver.api.core.servererrors.UnauthorizedException: User cluster_name_db_user has no CREATE permission on <all tables in reaper_db> or any of its parents`

but i am create ks cluster_name_cassandra_reaper and push full permission on that ks to user cluster_name_db_user

┆Issue is synchronized with this [Jira Story](https://datastax.jira.com/browse/REAP-216) by [Unito](https://www.unito.io)
┆Issue Number: REAP-216
