### ISSUE TITLE
java.lang.IllegalArgumentException: A health check named cassandra.cass-db-1 already exists

### ISSUE THREAD

**Issue by abe-1** [thelastpickle/cassandra-reaper#1580]
After cassandra is deployed and making sure cassandra is up and running in at least 3 pods (currently testing with 3 pods, each in one availability zone) reaper is deployed using the following manifest. the init container first creates the keyspace (even i tried adding drop keyspace reaper_db if exists; didn't help) and the container cassandar-reaper deploys and configure the reaper.
here is the full log
kubectl logs cass-db-1-cassandra-reaper-6666d759c4-58w2r -n cassandra-cass-db-1 -c cassandra-reaper    
WARN  [2025-06-17 18:15:52,635] com.datastax.driver.core.utils.UUIDs: PID returned through native call was 0, JNR versions incompatible?  Falling back to JMX.
INFO   [2025-06-17 18:16:03,229] [main] o.e.j.u.log - Logging initialized @12887ms to org.eclipse.jetty.util.log.Slf4jLog 
INFO   [2025-06-17 18:16:03,940] [main] i.d.s.DefaultServerFactory - Registering jersey handler with root path prefix: / 
INFO   [2025-06-17 18:16:03,943] [main] i.d.s.DefaultServerFactory - Registering admin handler with root path prefix: / 
INFO   [2025-06-17 18:16:03,944] [main] i.d.a.AssetsBundle - Registering AssetBundle with name: assets for path /webui/* 
INFO   [2025-06-17 18:16:04,733] [main] o.a.s.c.ReflectionBuilder - An instance with name 'authc' already exists.  Redefining this object as a new instance of type org.apache.shiro.web.filter.authc.PassThruAuthenticationFilter 
INFO   [2025-06-17 18:16:04,833] [main] o.a.s.c.ReflectionBuilder - An instance with name 'rest' already exists.  Redefining this object as a new instance of type io.cassandrareaper.resources.auth.RestPermissionsFilter 
INFO   [2025-06-17 18:16:05,024] [main] i.c.ReaperApplication - initializing runner thread pool with 15 threads and 2 repair runners 
INFO   [2025-06-17 18:16:05,025] [main] i.c.ReaperApplication - initializing storage of type: cassandra 
INFO   [2025-06-17 18:16:05,027] [main] i.c.s.InitializeStorage - Initializing the database and performing schema migrations 
INFO   [2025-06-17 18:16:05,326] [main] c.d.d.core - DataStax Java driver 3.11.5 for Apache Cassandra 
INFO   [2025-06-17 18:16:05,330] [main] c.d.d.c.GuavaCompatibility - Detected Guava >= 19 in the classpath, using modern compatibility layer 
INFO   [2025-06-17 18:16:05,927] [main] c.d.d.c.Native - Could not load JNR C Library, native system calls through this library will not be available (set this logger level to DEBUG to see the full stack trace). 
INFO   [2025-06-17 18:16:05,927] [main] c.d.d.c.ClockFactory - Using java.lang.System clock to generate timestamps. 
INFO   [2025-06-17 18:16:06,439] [main] c.d.d.c.NettyUtil - Did not find Netty's native epoll transport in the classpath, defaulting to NIO. 
INFO   [2025-06-17 18:16:09,026] [main] c.d.d.c.p.DCAwareRoundRobinPolicy - Using data-center name 'us-east-1' for DCAwareRoundRobinPolicy (if this is incorrect, please provide the correct datacenter name with DCAwareRoundRobinPolicy constructor) 
INFO   [2025-06-17 18:16:09,029] [main] c.d.d.c.Cluster - New Cassandra host cass-db-1-us-east-1-all-pods-service/10.62.116.33:9042 added 
INFO   [2025-06-17 18:16:09,030] [main] c.d.d.c.Cluster - New Cassandra host cass-db-1-us-east-1-all-pods-service/10.62.48.50:9042 added 
INFO   [2025-06-17 18:16:09,030] [main] c.d.d.c.Cluster - New Cassandra host cass-db-1-us-east-1-all-pods-service/10.62.174.135:9042 added 
INFO   [2025-06-17 18:16:10,161] [main] i.c.s.c.CassandraStorageFacade - Skipping schema migration as requested. 
ERROR  [2025-06-17 18:16:10,234] [main] i.c.ReaperApplication - Storage is not ready yet, trying again to connect shortly... 
com.datastax.driver.core.exceptions.InvalidQueryException: table diagnostic_event_subscription does not exist
	at com.datastax.driver.core.exceptions.InvalidQueryException.copy(InvalidQueryException.java:50)
	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:35)
	at com.datastax.driver.core.AbstractSession.prepare(AbstractSession.java:86)
	at io.cassandrareaper.storage.events.CassandraEventsDao.prepareStatements(CassandraEventsDao.java:46)
	at io.cassandrareaper.storage.events.CassandraEventsDao.<init>(CassandraEventsDao.java:42)
	at io.cassandrareaper.storage.cassandra.CassandraStorageFacade.<init>(CassandraStorageFacade.java:147)
	at io.cassandrareaper.storage.InitializeStorage.initializeStorageBackend(InitializeStorage.java:68)
	at io.cassandrareaper.ReaperApplication.tryInitializeStorage(ReaperApplication.java:456)
	at io.cassandrareaper.ReaperApplication.run(ReaperApplication.java:180)
	at io.cassandrareaper.ReaperApplication.run(ReaperApplication.java:90)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:67)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:98)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:94)
	at io.cassandrareaper.ReaperApplication.main(ReaperApplication.java:102)
Caused by: com.datastax.driver.core.exceptions.InvalidQueryException: table diagnostic_event_subscription does not exist
	at com.datastax.driver.core.Responses$Error.asException(Responses.java:193)
	at com.datastax.driver.core.SessionManager$4.apply(SessionManager.java:249)
	at com.datastax.driver.core.SessionManager$4.apply(SessionManager.java:218)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:211)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:200)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:111)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:992)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
INFO   [2025-06-17 18:16:20,235] [main] i.c.s.InitializeStorage - Initializing the database and performing schema migrations 
WARN   [2025-06-17 18:16:20,236] [main] i.c.s.c.CassandraStorageFacade - Customization of cassandra's retry policy is not supported and will be overridden 
INFO   [2025-06-17 18:16:20,236] [main] c.d.d.c.ClockFactory - Using java.lang.System clock to generate timestamps. 
INFO   [2025-06-17 18:16:20,829] [main] c.d.d.c.p.DCAwareRoundRobinPolicy - Using data-center name 'us-east-1' for DCAwareRoundRobinPolicy (if this is incorrect, please provide the correct datacenter name with DCAwareRoundRobinPolicy constructor) 
INFO   [2025-06-17 18:16:20,835] [main] c.d.d.c.Cluster - New Cassandra host cass-db-1-us-east-1-all-pods-service/10.62.116.33:9042 added 
INFO   [2025-06-17 18:16:20,835] [main] c.d.d.c.Cluster - New Cassandra host cass-db-1-us-east-1-all-pods-service/10.62.48.50:9042 added 
INFO   [2025-06-17 18:16:20,835] [main] c.d.d.c.Cluster - New Cassandra host cass-db-1-us-east-1-all-pods-service/10.62.174.135:9042 added 
ERROR  [2025-06-17 18:16:21,324] [main] i.c.ReaperApplication - Storage is not ready yet, trying again to connect shortly... 
java.lang.IllegalArgumentException: A health check named cassandra.cass-db-1 already exists
	at com.codahale.metrics.health.HealthCheckRegistry.register(HealthCheckRegistry.java:101)
	at systems.composable.dropwizard.cassandra.CassandraFactory.build(CassandraFactory.java:505)
	at systems.composable.dropwizard.cassandra.CassandraFactory.build(CassandraFactory.java:447)
	at io.cassandrareaper.storage.cassandra.CassandraStorageFacade.<init>(CassandraStorageFacade.java:124)
	at io.cassandrareaper.storage.InitializeStorage.initializeStorageBackend(InitializeStorage.java:68)
	at io.cassandrareaper.ReaperApplication.tryInitializeStorage(ReaperApplication.java:456)
	at io.cassandrareaper.ReaperApplication.run(ReaperApplication.java:180)
	at io.cassandrareaper.ReaperApplication.run(ReaperApplication.java:90)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:67)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:98)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:94)
	at io.cassandrareaper.ReaperApplication.main(ReaperApplication.java:102)

and this is manifest file for reaper where the reaper_server_version: 3.4.0

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-cassandra-reaper" .Values.global.db_cluster_name }}
  annotations:
    argocd.argoproj.io/sync-wave: "16"
  namespace: {{ .Values.global.namespace }}
  labels:
    app: cassandra-reaper
spec:
  telemetry:
    prometheus:
      enabled: true
  replicas: 1
  selector:
    matchLabels:
      app: cassandra-reaper
  template:
    metadata:
      labels:
        app: cassandra-reaper
    spec:
      volumes:
        - name: certs
          secret:
            secretName: {{ printf "%s-cluster-certificate-secret" .Values.global.db_cluster_name }}
        - name: tmp
          emptyDir: {}
      initContainers:
        - name: reaper-keyspace-init
          image: "cassandra:{{ .Values.cassandra.server_version }}"
          command: ["/bin/sh", "-c"]
          env:
            - name: CASS_USER
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-superuser" .Values.global.db_cluster_name }}
                  key: username
            - name: CASS_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-superuser" .Values.global.db_cluster_name }}
                  key: password
            - name: INIT_CQL
              value: >
                CREATE KEYSPACE IF NOT EXISTS reaper_db
                WITH replication = {'class': 'NetworkTopologyStrategy', '{{ .Values.global.region }}': 1 }
          args:
            - |-
                  HOME=/opt/cassandra /opt/cassandra/bin/cqlsh --protocol-version=5 --ssl --cqlshrc=/opt/cassandra/.cassandra/cqlshrc \
                  {{ printf "%s-%s-service" .Values.global.db_cluster_name .Values.global.region }} \
                  -u $CASS_USER -p $CASS_PASS -e "$INIT_CQL" &&
                  break;
      containers:
        - name: cassandra-reaper
          image: "thelastpickle/cassandra-reaper:{{ .Values.reaper.reaper_server_version }}"
          volumeMounts:
            - name: certs
              mountPath: "/crypto"
          env:
          - name: REAPER_CASS_AUTH_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ printf "%s-superuser" .Values.global.db_cluster_name }}
                key: username
          - name: REAPER_CASS_AUTH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ printf "%s-superuser" .Values.global.db_cluster_name }}
                key: password
          - name: REAPER_CASS_AUTH_ENABLED
            value: "true"
          - name: REAPER_SKIP_SCHEMA_MIGRATION
            value: "true"
          - name: LOGGING_LEVEL
            value: DEBUG
          - name: REAPER_STORAGE_TYPE
            value: cassandra
          - name: REAPER_CASS_CLUSTER_NAME
            value: "{{ .Values.global.db_cluster_name }}"
          - name: REAPER_CASS_CONTACT_POINTS
            value: '["{{ printf "%s-%s-all-pods-service" .Values.global.db_cluster_name .Values.global.region }}"]'
          - name: REAPER_ENABLE_WEBUI_AUTH
            value: "true"
          - name: REAPER_WEBUI_USER
            value: "{{ .Values.secrets.reaper_web_ui_user }}"
          - name: REAPER_WEBUI_PASSWORD
            value: "{{ .Values.secrets.reaper_web_ui_password }}"
          - name: REAPER_CASS_NATIVE_PROTOCOL_SSL_ENCRYPTION_ENABLED
            value: "true"
          - name: REAPER_KEYSTORE_PASS
            valueFrom:
              secretKeyRef:
                name: {{ printf "%s-keystore-password" .Values.global.db_cluster_name }}
                key: password
          - name: JAVA_OPTS
            value: "-Dssl.enable=true -Djavax.net.ssl.keyStore=/crypto/keystore.jks  -Djavax.net.ssl.trustStore=/crypto/truststore.jks  -Djavax.net.ssl.keyStorePassword=$(REAPER_KEYSTORE_PASS) -Djavax.net.ssl.trustStorePassword=$(REAPER_KEYSTORE_PASS)"
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 30
          resources:
            requests:
              cpu: 200m
              memory: 400Mi
            limits:
              cpu: 300m
              memory: 1024Mi
          ports:
          - containerPort: 8081
            name: 'admin-ui'
          - containerPort: 8080
            name: 'web-ui'
```

┆Issue is synchronized with this [Jira Story](https://datastax.jira.com/browse/REAP-220) by [Unito](https://www.unito.io)
┆Issue Number: REAP-220
