### ISSUE TITLE
Cannot able to connect in Cassandra Host

### ISSUE THREAD

**Issue by antikilahdjs** [thelastpickle/cassandra-reaper#1585]
Hello guys, 

I am sorry to ask it but am trying configure my Reaper to connect in my existing cassandra but am not able to do it. I saw the all documentation but am so frustated with that. 

Coul you please help me to understand what I did wrong ?

![Image](https://github.com/user-attachments/assets/aae12f45-98db-4fd7-a48e-8fb8b03aced1)

This is my Kubernetes YAML

```yaml
spec:
      containers:
        - name: cassandra-reaper-container
          image: 'thelastpickle/cassandra-reaper:master'
          ports:
            - name: http-reaper-web
              containerPort: 8080
              protocol: TCP
            - name: http-jmx-casc
              containerPort: 8081
              protocol: TCP
          env:
            - name: REAPER_AUTH_ENABLED
              value: 'no'
            - name: REAPER_CASS_CLUSTER_NAME
              value: cassandra
            - name: REAPER_CASS_AUTH_USERNAME
              value: cassandra
            - name: REAPER_CASS_KEYSPACE
              value: inferences
            - name: REAPER_CASS_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cassandra-data-contract
                  key: cassandra-password
            - name: REAPER_CASS_CONTACT_POINTS
              value: my_cassandra_kubernetes
            - name: REAPER_CASS_PORT
              value: '9042'
            - name: REAPER_DATACENTER_AVAILABILITY
              value: ALL
```

┆Issue is synchronized with this [Jira Story](https://datastax.jira.com/browse/REAP-221) by [Unito](https://www.unito.io)
┆Issue Number: REAP-221
