### ISSUE TITLE
SegmentCountPerNode and SegmentCount issues

### ISSUE THREAD

**Issue by Ahuri3** [thelastpickle/cassandra-reaper#421]
I updated from cassandra-reaper `0.6.1` to `1.1.0` today in our preproduction environment. 

I noticed was that the new parameter `SegmentCountPerNode` seems to have replaced `SegmentCount`.

Before the upgrade `SegmentCount` was set to `1024`.
After the upgrade I set `SegmentCountPerNode` to `256` and removed `SegmentCount`.

## First issue : `SegmentCount` still exists ?

I noticed that : 
```
spreaper list-schedules
# Report improvements/bugs at https://github.com/thelastpickle/cassandra-reaper/issues
# ------------------------------------------------------------------------------------
# Listing repair schedules for all clusters
# Found  schedules:
[
  {
    "blacklisted_tables": [], 
    "cluster_name": "clustername", 
    "column_families": [], 
    "creation_time": "2018-05-16T16:02:3
    "datacenters": [], 
    "id": "00000000-0000-000a-0000-000000000000", 
    "incremental_repair": true, 
    "intensity": 0.500, 
    "keyspace_name": "keyspace_name", 
    "next_activation": "2018-05-16T22:07:38Z", 
    "nodes": [], 
    "owner": "auto-scheduling", 
    "pause_time": null, 
    "repair_parallelism": "PARALLEL", 
    "scheduled_days_between": 3, 
    "segment_count": 0, 
    "segment_count_per_node": 256, 
    "state": "ACTIVE"
  }
```

The part that worries me is : 
```
    "segment_count": 0, 
    "segment_count_per_node": 256, 
```
Is `SegmentCount` still supposed to be defined ? It's not in the documentation anymore.
I can still find it in the source code and the docker page of the documentation.

## Second issue : `SegmentCountPerNode` is ignored ?

The `SegmentCountPerNode` value seemsto be completely ignored.
Here is the repair run currently running : 
```
spreaper list-runs
# Report improvements/bugs at https://github.com/thelastpickle/cassandra-reaper/issues
# ------------------------------------------------------------------------------------
# Listing repair runs
# Found 1 repair runs
[
  {
    "blacklisted_tables": [], 
    "cause": "scheduled run (schedule id 00000000-0000-0008-0000-000000000000)", 
    "cluster_name": "pp-op-cass00", 
    "column_families": [], 
    "creation_time": "2018-05-16T16:07:51Z", 
    "datacenters": [], 
    "duration": null, 
    "end_time": null, 
    "estimated_time_of_arrival": null, 
    "id": "00000000-0000-0003-0000-000000000000", 
    "incremental_repair": true, 
    "intensity": 0.500, 
    "keyspace_name": "kairosdb", 
    "last_event": "Postponed due to already running segment", 
    "nodes": [], 
    "owner": "auto-scheduling", 
    "pause_time": null, 
    "repair_parallelism": "PARALLEL", 
    "segments_repaired": 0, 
    "start_time": "2018-05-16T16:07:51Z", 
    "state": "RUNNING", 
    "total_segments": 3
  }
```

You can notice that the amount of segments isn't coherent with the `SegmentCountperNode` : 
```
    "total_segments": 3
```

Am I missing something ?

**Comment by adejanovski** [comment]
Hi @Ahuri3,

`segment_count` is still there for backward compatibility. We didn't want people to have to update all existing schedules.
What happens is that if a value exists for `segment_count`, it will be used instead of `segment_count_per_node`.
Apparently there's a bug in `spreaper` which does not set the new `segmentCountPerNode` setting.

What happens here is that it uses the `0` in `segment_count` since it exists, and you must have 3 nodes in your cluster with no vnodes. This leads to generating as few segments as possible, which is 3.

I recommend to delete the schedule and create a through the UI for now, and I'll create a PR to fix the issue in `spreaper`.

**Comment by Ahuri3** [comment]
I will first try : 

- Check that `SegmentCount` isn't set anywhere (only `SegmentCountperNode`) (I'll search a dump of the darabase).
- To delete the schedules/clusters entirely 
- Manually add the clusters from the webui 
- Let the auto-scheduling do it's job now that SegmentCount isn't in the configuration file.
- Check the runs


If it doesn't work : 
- Delete the schedules/clusters entirely
- Manually add the clusters from the webui 
- Manually add the schedules
- Check the runs

If nothing works I'll probably erase the database in order to have a 100% clean installation. 

Right now the database was erased (manually) during the update, but reaper may have been started with an incorrect configuration file (with `SegmentCount` and without `SegmentCountPerNode`). 

I want to try everything in case I can find a way to get it to work

## Some extra information : 

### About the Schedule 

The schedule in my initial post was generated by the auto-scheduling, I just used spreaper to display the information since it easier to copy/paste into a github issue.

I don't know if the auto-scheduling feature uses spreaper to work, but the schedules were not manually set via spreaper.

However the clusters were added via spreaper.

### About my cassandra cluster

> What happens here is that it uses the 0 in segment_count since it exists, and you must have 3 nodes in your cluster with no vnodes. This leads to generating as few segments as possible, which is 3.

All of my cassandra nodes have `num_tokens: 256` my understanding is that they have vnodes. So this might not be the cause of the issue.

### My configuration : 

Here is an edited copy of the reaper configuration I use. I should have provided it with my initial post : 
```
~# cat /etc/spotify/cassandra-reaper.yaml 

# Cassandra Reaper Configuration Example.
# See a bit more complete example in:
# src/test/resources/cassandra-reaper.yaml
segmentCountPerNode: 256
repairParallelism: parallel
repairIntensity: 0.5
scheduleDaysBetween: 3
repairRunThreadCount: 60
hangingRepairTimeoutMins: 30
storageType: postgres
enableCrossOrigin: true
incrementalRepair: true
enableDynamicSeedList: true
repairManagerSchedulingIntervalSeconds: 30

jmxPorts:
  127.0.0.1: 7100
  127.0.0.2: 7200
  127.0.0.3: 7300
  127.0.0.4: 7400
  127.0.0.5: 7500
  127.0.0.6: 7600
  127.0.0.7: 7700
  127.0.0.8: 7800

jmxAuth:
  username: username
  password: password

logging:
  level: INFO
  loggers:
    io.dropwizard: INFO
    org.eclipse.jetty: INFO
  appenders:
    - type: console
      logFormat: "%-6level %logger{5} - %msg %n"

server:
  type: default
  applicationConnectors:
    - type: http
      port: 8080
      bindHost: 127.0.0.1
  adminConnectors:
    - type: http
      port: 8081
      bindHost: 127.0.0.1
  requestLog:
    appenders: []

postgres:
  # PostgreSQL JDBC settings
  driverClass: org.postgresql.Driver
  user: reaper
  url: jdbc:postgresql://127.0.0.1/reaper

autoScheduling:
  enabled: True
  initialDelayPeriod: PT180S
  periodBetweenPolls: PT10M
  timeBeforeFirstSchedule: PT5M
  scheduleSpreadPeriod: PT6H
```

The systemd unit used to launch reaper : 
```
# /etc/systemd/system/reaper.service

[Unit]
Description=Cassandra-Reaper Daemon

[Service]
Type=simple
User=reaper
Group=reaper
Restart=on-failure
ExecStart=/usr/bin/java -jar /usr/local/share/cassandra-reaper/target/cassandra_reaper.jar server /etc/spotify/cassandra-reaper.yaml
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=reaper

[Install]
WantedBy=multi-user.target
```
