### ISSUE TITLE
[1.2.0] Login.html broken (blank page)

### ISSUE THREAD

**Issue by nsteinmetz** [thelastpickle/cassandra-reaper#467]
Hello,

I just activated accessControl but the page remains blank where as ressources are loaded. Before accessControl, app worked as expected.

My `cassandra-reaper.yaml` file:

```yaml
# Cassandra Reaper Configuration Example.
# See a bit more complete example in:
# src/server/src/test/resources/cassandra-reaper.yaml
segmentCountPerNode: 16
repairParallelism: DATACENTER_AWARE
repairIntensity: 0.9
scheduleDaysBetween: 7
repairRunThreadCount: 15
hangingRepairTimeoutMins: 30
storageType: cassandra
enableCrossOrigin: true
incrementalRepair: false
enableDynamicSeedList: true
repairManagerSchedulingIntervalSeconds: 10
activateQueryLogger: false
jmxConnectionTimeoutInSeconds: 5
useAddressTranslator: false
# purgeRecordsAfterInDays: 30
# numberOfRunsToKeepPerUnit: 10

# datacenterAvailability has three possible values: ALL | LOCAL | EACH
# the correct value to use depends on whether jmx ports to C* nodes in remote datacenters are accessible
# If the reaper has access to all node jmx ports, across all datacenters, then configure to ALL.
# If jmx access is only available to nodes in the same datacenter as reaper in running in, then configure to LOCAL.
# If there's a reaper instance running in every datacenter, and it's important that nodes under duress are not involved in repairs,
#    then configure to EACH.
#
# The default is ALL
datacenterAvailability: ALL

jmxPorts:
  127.0.0.1: 7199

logging:
  level: INFO
  loggers:
    io.dropwizard: WARN
    org.eclipse.jetty: WARN

  appenders:
    - type: console
      logFormat: "%-6level [%d] [%t] %logger{5} - %msg %n"
      threshold: WARN
    - type: file
      logFormat: "%-6level [%t] %logger{5} - %msg %n"
      currentLogFilename: /var/log/cassandra-reaper/reaper.log
      archivedLogFilenamePattern: /var/log/cassandra-reaper/reaper-%d.log.gz
      archivedFileCount: 99

server:
  type: default
  applicationConnectors:
    - type: http
      port: 8080
      bindHost: 0.0.0.0
  adminConnectors:
    - type: http
      port: 8082
      bindHost: 0.0.0.0
  requestLog:
    appenders: []

storageType: cassandra
cassandra:
  clusterName: "test"
  contactPoints: ["127.0.0.1"]
  keyspace: reaper_db
  queryOptions:
    consistencyLevel: LOCAL_QUORUM
    serialConsistencyLevel: SERIAL

autoScheduling:
  enabled: false
  initialDelayPeriod: PT15S
  periodBetweenPolls: PT10M
  timeBeforeFirstSchedule: PT5M
  scheduleSpreadPeriod: PT6H
  excludedKeyspaces:
    - keyspace1
    - keyspace2

accessControl:
  sessionTimeout: PT10M
  shiro:
    iniConfigs: ["file:/etc/cassandra-reaper/shiro.ini"]
```

My `/etc/cassandra-reaper/shiro.ini` file (owner: reaper, mod: 0644):

```ini
[main]
authc = org.apache.shiro.web.filter.authc.PassThruAuthenticationFilter
authc.loginUrl = /webui/login.html

[users]
user1 = password1
user2 = password2

[urls]
/webui/ = authc
/webui = authc
/webui/login.html = anon
/webui/*.html* = authc
/webui/*.js* = anon
/ping = anon
/login = anon
/** = anon
```

When I'm redirected to /web/login.html, I have a white page even if code is:

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Cassandra Reaper - Login</title>
    <!-- <base href="/webui/"> -->
    <base href="" />
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
<script type="text/javascript" src="deps.js?776b59761ee637e5bb54"></script><script type="text/javascript" src="login.js?776b59761ee637e5bb54"></script></head>
<body>
    <div id="wrapper">
    </div>
    <!-- /#wrapper -->
</body>
</html>

```

Only error message is :

![capture d ecran 2018-07-09 a 19 06 12](https://user-images.githubusercontent.com/33180/42465461-50e22150-83ac-11e8-8db4-961ac7d061c8.png)

I have nginx on top of reaper but direct access lead to same result. So it's not a nginx issue.
