### ISSUE TITLE
Error when starting cassandra-reaper service

### ISSUE THREAD

**Issue by vvaldersteins** [thelastpickle/cassandra-reaper#596]
Hi,

So I have a cassandra cluster setup with 3 nodes. On each node JMX authentication is enabled based on this tutorial - https://docs.datastax.com/en/cassandra/3.0/cassandra/configuration/secureJmxAuthentication.html . In additional to that, I have updated `cassandra-reaper.yaml` with the following lines -

```
storageType: cassandra
cassandra:
  clusterName: "test_cluster"
  contactPoints: ["my_ip_adress"]
  keyspace: reaper_db
  authProvider:
    type: plainText
    username: myUsername
    password: myPassword
``` 

NOTE: I have changed my_ip_address with seed node IP address, and myUsername and myPassword with actual username and password.

I have created the reaper_db with the following command (All of my nodes are in single data center) -
```
CREATE keyspace reaper_db with replication = { 'class': 'SimpleStrategy', 'replication_factor': 3};
```

Finally after like 5 minutes of starting up the cassandra reaper service (keep in mind that it does not start up, but does the migration part, and fails), I keep getting these messages -

```
[2018-12-18 12:20:14,652] [my-worker-0] c.d.d.c.Cluster - No schema agreement from live replicas after 10 s. The schema may not be up to date on some nodes.
```

This shows up few times (after migration has started to run), and then it gives an error message, that it cannot delete a table that does not exist. If I check the reaper_db, I can see some of the tables getting populated, and then again, they disappear, and only few of them stays there.

My cassandra version is 3.11.2.

Any ideas what could cause the issue?
