### ISSUE TITLE
Enable native SSL for webui and api

### ISSUE THREAD

**Issue by andrejvanderzee** [thelastpickle/cassandra-reaper#790]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=13937803)

We are moving from opscenter to Reaper. How can we serve reaper with TLS, without setting up a proxy?

I am missing SSL config options:

```
server:
  type: default
  applicationConnectors:
    - type: http
      port: 8080
      bindHost: 0.0.0.0
  adminConnectors:
    - type: http
      port: 8081
      bindHost: 0.0.0.0
```

┆Issue is synchronized with this [Jira Story](https://datastax.jira.com/browse/REAP-147) by [Unito](https://www.unito.io)
┆Issue Number: REAP-147
