### ISSUE TITLE
Provide a way to encrypt password in authProvider

### ISSUE THREAD

**Issue by Payal147** [thelastpickle/cassandra-reaper#802]
Provide a way to encrypt password in authProvider in Cassandra section while using Cassandra as storageType.

"storageType: cassandra
cassandra:
  clusterName: "test"
  contactPoints: ["127.0.0.1"]
  keyspace: reaper_db
  authProvider:
    type: plainText
    username: cassandra
    password: cassandra"

There should be a way to provide an encrypted password.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-412) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-412

**Comment by denniskline** [comment]
@Payal147 I have a workaround for this that I can contribute (at least to help this discussion along) that is based on Spring's implementation of encrypted credentials.

It boils down to a custom dropwizard AuthProviderFactory and a change to the config.yaml to reference it.  The authProvider then looks for a system property whose key is defined in systemPropertySecret for the value to decipher the password.

```
  authProvider:
    type: encryptedText
    username: "myusername"
    password: "{cipher}e3a055c901e71c12f0a2f762f30a561bfd01c97d5ecbb430698b99025560144a"
    systemPropertySecret: SYS_PROPERTY_ENCRYPTION_KEY
```
