### ISSUE TITLE
Configuration for translation of IP addresses received from Cassandra nodes into locally queriable addresses

### ISSUE THREAD

**Issue by maxshel** [thelastpickle/cassandra-reaper#832]
Provide a possibility to configure simple address translator for Cassandra storage connection and and for JMX connection. 
Sometimes it’s not possible for Cassandra nodes to broadcast addresses that will work for each and every client; for instance, they might broadcast private IPs because most clients are in the same network, but a particular client could be on another network and go through a router. For such cases, you can configure a custom address translator that will perform additional address translation based on configured mapping.

```yaml
cassandra: 
  clusterName: "test"
  contactPoints: ["node1.cassandra.reaper.io", "node2.cassandra.reaper.io"]
  keyspace: reaper_db
  jmxAddressTranslator:
    type: multiIpPerNode
    ipTranslations:
      - from: "10.10.10.111"
        to: "node1.cassandra.reaper.io"
      - from: "10.10.10.112"
        to: "node2.cassandra.reaper.io"
```

When running multi region clusters in AWS, we could set type to ec2MultiRegion in order to use the EC2MultiRegionAddressTranslator from the Datastax Java Driver.

Similar configuration can be used for JMX connection:

```yaml
jmxAddressTranslator:
  type: multiIpPerNode
  ipTranslations:
    - from: "10.10.10.111"
      to: "node1.cassandra.reaper.io"
    - from: "10.10.10.112"
      to: "node2.cassandra.reaper.io"
```
